### ISSUE TITLE
Update from 0.12.1 to 0.12.4 fails

### ISSUE THREAD

**Issue by tretkowski** [jippi/docker-pixelfed#73]
I tried to upgrade from 0.12.1 to 0.12.4, but starting the Pixelfed containers fails:

```
[entrypoint / entrypoint.sh] - ============================================================
[entrypoint / entrypoint.sh] - Executing [/docker/entrypoint.d/10-storage.sh]
[entrypoint / entrypoint.sh] - ============================================================
[entrypoint / 10-storage.sh] - 👷 Running [cp --force --recursive storage.skel/. ./storage/] as [www-data]
[entrypoint / 10-storage.sh] - ✅ OK!
[entrypoint / 10-storage.sh] - 👷 Running [php artisan storage:link] as [www-data]
[entrypoint / 10-storage.sh] - (stderr) [2024-11-30 17:46:43] production.ERROR: Class "BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BeyondCode\LaravelWebSockets\WebSocketsServiceProvider\" not found at /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:933)
[entrypoint / 10-storage.sh] - (stderr) [stacktrace]
[entrypoint / 10-storage.sh] - (stderr) #0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(865): Illuminate\Foundation\Application->resolveProvider()
[entrypoint / 10-storage.sh] - (stderr) #1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\Foundation\Application->register()
[entrypoint / 10-storage.sh] - (stderr) #2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(843): Illuminate\Foundation\ProviderRepository->load()
[entrypoint / 10-storage.sh] - (stderr) #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(37): Illuminate\Foundation\Application->registerConfiguredProviders()
[entrypoint / 10-storage.sh] - (stderr) #4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap()
[entrypoint / 10-storage.sh] - (stderr) #5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(473): Illuminate\Foundation\Application->bootstrapWith()
[entrypoint / 10-storage.sh] - (stderr) #6 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\Foundation\Console\Kernel->bootstrap()
[entrypoint / 10-storage.sh] - (stderr) #7 /var/www/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
[entrypoint / 10-storage.sh] - (stderr) #8 {main}
[entrypoint / 10-storage.sh] - (stderr) "}
[entrypoint / 10-storage.sh] - (stdout) 
[entrypoint / 10-storage.sh] - (stdout) In Application.php line 933:
[entrypoint / 10-storage.sh] - (stdout) 
[entrypoint / 10-storage.sh] - (stdout) Class "BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" not found
[entrypoint / 10-storage.sh] - (stdout) 
[entrypoint / 10-storage.sh] - (stdout) 
[entrypoint / 10-storage.sh] - ERROR - ❌ Error!
```

A new 0.12.4 deployment works fine.

**Comment by jippi** [comment]
Hi,

You need to either use `scripts/update` or manually remove the file cache (https://github.com/jippi/docker-pixelfed/blob/main/scripts/update#L48-L50)
